apiVersion: batch/v1
kind: CronJob
metadata:
  name: datacenter
spec:
  schedule: "*/7 * * * *" # cronjob will run for evevry 7 mins
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nginx-cron-datacenter
            image: nginx:latest
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
 
######Run below commands
 
#kubectl create -f <file path> -->create cronjob
#kubectl get cronjob datacenter --> gets the status of above cronjob
#kubectl get jobs --watch  --> the cron job has not scheduled or run any jobs yet
