apiVersion: v1
kind: Service
metadata:
  name: centos-ssh-node-service
spec:
  selector:
    app: centos-ssh-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30012
  type: NodePort
