apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: nautilus
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort
